import 'package:cloud_firestore/cloud_firestore.dart';

class DevelopmentReport {
  final String id;
  final String institutionId;
  final String sessionId; // Belongs to which session
  final String targetId; // Replaces studentId
  final String targetType; // 'student', 'teacher', 'personnel'
  final String
  term; // e.g., "2023-2024 Spring", fallback for legacy/compatibility or title
  final String schoolYear; // e.g., "2023-2024"

  // Scores organized by category -> subCategory -> score
  // Example: {'academic': 85.0, 'social': 90.0}
  final Map<String, double> categoryScores;

  // Detailed analysis generated by AI or calculated
  final Map<String, dynamic> analysis;

  // Metadata
  final String status; // 'draft', 'published'
  final DateTime createdAt;
  final DateTime? updatedAt;
  final double? riskScore;
  final double? growthIndex;

  DevelopmentReport({
    required this.id,
    required this.institutionId,
    this.sessionId = '',
    required this.targetId,
    this.targetType = 'student',
    required this.term,
    required this.schoolYear,
    this.categoryScores = const {},
    this.analysis = const {},
    this.status = 'draft',
    required this.createdAt,
    this.updatedAt,
    this.riskScore,
    this.growthIndex,
  });

  factory DevelopmentReport.fromMap(Map<String, dynamic> map) {
    // Backwards compatibility for old records with studentId
    String targetId = map['targetId'] ?? map['studentId'] ?? '';
    String targetType = map['targetType'] ?? 'student';

    return DevelopmentReport(
      id: map['id'] ?? '',
      institutionId: map['institutionId'] ?? '',
      sessionId: map['sessionId'] ?? '',
      targetId: targetId,
      targetType: targetType,
      term: map['term'] ?? '',
      schoolYear: map['schoolYear'] ?? '',
      categoryScores: Map<String, double>.from(
        (map['categoryScores'] ?? {}).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        ),
      ),
      analysis: Map<String, dynamic>.from(map['analysis'] ?? {}),
      status: map['status'] ?? 'draft',
      createdAt: (map['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt: (map['updatedAt'] as Timestamp?)?.toDate(),
      riskScore: (map['riskScore'] as num?)?.toDouble(),
      growthIndex: (map['growthIndex'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'institutionId': institutionId,
      'sessionId': sessionId,
      'targetId': targetId,
      'targetType': targetType,
      'term': term,
      'schoolYear': schoolYear,
      'categoryScores': categoryScores,
      'analysis': analysis,
      'status': status,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
      'riskScore': riskScore,
      'growthIndex': growthIndex,
    };
  }
}
