import '../../survey_model.dart';
import 'guidance_test_definition.dart';

class AcademicSelfConceptTest extends GuidanceTestDefinition {
  @override
  String get id => 'academic_self_concept_v1';

  @override
  String get title => 'Akademik Benlik Kavramı Ölçeği (ABKÖ)';

  @override
  String get description =>
      'Bu ölçek, yetenekleriniz ve ilgi alanlarınız hakkında farkındalık kazanmanıza yardımcı olmak amacıyla hazırlanmıştır. 170 sorudan oluşan bu çalışmada her soru için size en uygun seçeneği (A, B, C veya D) işaretleyiniz. Bu bir sınav değildir ve "doğru" ya da "yanlış" cevabı yoktur. Lütfen her soru için kendinizi en iyi yansıtan seçeneği seçerek ilerleyiniz.';

  @override
  List<SurveySection> get sections => [
    SurveySection(
      id: 'yetenek_bolumu',
      title: '1. Bölüm: Yetenekler',
      questions: _getYetenekQuestions(),
    ),
    SurveySection(
      id: 'ilgi_bolumu',
      title: '2. Bölüm: İlgi Alanları',
      questions: _getIlgiQuestions(),
    ),
  ];

  List<SurveyQuestion> _getYetenekQuestions() {
    final List<String> texts = [
      'Bir yazı yazarken, bir ödev yaparken, yazım (imla) kurallarına dikkat eder misiniz?',
      'Bir hikaye kitabını hızlı ve doğru okuyabilir misiniz?',
      'Çarpım tablosunu, bölme işlemini kolay öğrenebildiniz mi?',
      'Birbirine çok benzeyen iki resmin arasındaki küçük farkları hemen görebilir misiniz?',
      'Kelimeleri doğru bir biçimde yazabiliyor ve söylebiliyor musunuz?',
      'Bir dairenin merkezini doğru bir biçimde tahmin ederek işaretleyebilir misiniz?',
      'İki çizgi arsında çok az bir uzunluk farkı olduğunda, bunu kolaylıkla algılayabilir misiniz?',
      'Bir parçayı bir kere okuduktan sonra hemen özetleyebiliyor musunuz?',
      'Dört işlemle akıldan, hızlı problem çözebilir misiniz?',
      'Bir doğru parçasının kaç santimetre olduğunu doğru tahmin edebilir misiniz?',
      'Yeni duyduğunuz kelimelerin anlamlarını öğrenmeye çalışır mısınız?',
      'Okuduğunuz bir parçada belirten fikirler arsında ilişki kurabiliyor musunuz?',
      'Bir matematik probleminin çözüm yolunu öğrendikten sonra, ona benzer problemleri çözebiliyor musunuz?',
      'İlk defa gittiğiniz binada yönünüzü bulabiliyor musunuz?',
      'Bir defa başkaları ile birlikte gittiğiniz bir yeri, ikinci defa yalnız başına gittiğinizde, kolaylıkla bulabilir misiniz?',
      'Gelişigüzel parçaları ayrılmış bir şeklin veya cismin parçalarını eski yerlerine kolaylıkla yerleştirebilir misiniz?',
      'Bir makinanın şemasına bakarak makineyi kurabilir misiniz?',
      'Açılmış hali verilen geometrik bir cismin, kapandığı zaman açılacağı şekli göz önünde canlandırabilir misiniz?',
      'Bir konuda edindiğiniz bilgileri, kendi sözcüklerinizle başkalarına aktarabiliyor musunuz?',
      'Sizin düzeyinizde bir matematik kitabını okuyarak bir problemin çözüm yolunu bulabiliyor musunuz?',
      'Boş zamanlarınızda, zevk için matematik problemleri çözmeye çalışır mısınız?',
      'Bir konuyu söz ve yazı ile anlatırken, fikirleri doğru bir sıra ile verebiliyor musunuz?',
      'Matematik dersinde, özel bir yardım (ders) almadan başarılı olabiliyor musunuz?',
      'Bir yazıdaki fikir ve ifade hatalarını kolaylıkla görebilir misiniz?',
      'Boş bir kesme şeker kutusu, kısa kenarlarından kesilip açılınca hangi yüzeyin nereye geleceğini gözönünde canlandırabilir misiniz?',
      'Öğrendiğiniz matematik kurallarına fen bilgisi derslerindeki problemlere uygulayabiliyor musunuz?',
      'Bir kağıda, cetvel kullanmadan düzgün paralel çizgiler çizebiliyor musunuz?',
      'Karmaşık bir geometrik şeklin, sağa ve sola döndürülmesi ile alacağı durumu gözönünde canlandırabilir misiniz?',
      'Bir problemin, size öğretilen çözüm yollarından farklı çözüm yollarını bulabilir misiniz?',
      'Akıcı bir üslupla güzel yazı (örneğin bir mektup) yazabilir misiniz?',
      'Okuduğunuz bir parçada anlatılan fikirleri bulup özetleyebiliyor musunuz?',
      'Sizin düzeyinde, ama daha önce hiç görmediğiniz bir matematik kitabını rahatlıkla okuyabilir misiniz?',
      'Bir evin planına baktığınızda, evin yapılmış halini gözönünde canlandırabilir misiniz?',
      'Bir kağıda çizilen yıldız biçimindeki bir şekli makasla, düzgün bir biçimde kesip çıkarabilir misiniz?',
      'Alet kullanmadan düzgün geometrik şekiller çizebilir misiniz?',
      'Attığınız bir bilyeyi veya bir taşı istediğiniz hedefe gönderebilir misiniz?',
    ];

    return List.generate(texts.length, (i) {
      return SurveyQuestion(
        id: 'q${i + 1}',
        text: texts[i],
        type: SurveyQuestionType.singleChoice,
        isRequired: true,
        options: ['A', 'B', 'C', 'D'],
      );
    });
  }

  List<SurveyQuestion> _getIlgiQuestions() {
    final List<String> texts = [
      'Satranç öğrenmek için çaba sarfediyor musunuz?', // 37
      'Fen dersleri ile ilgili konuları kolay öğrenebiliyor musunuz?',
      'Desenli kağıtları, şekilleri birbirine tamamlayacak şekilde, yanyana yapıştırabilir misiniz?',
      'Bir aletin (örneğin, saatin) çok küçük bir parçasını (vidasını) yerine kolayca yerleştirebilir misiniz?',
      'Gelecekte kendinizi, laboratuarda araştırmacı olarak düşlediğiniz oldumu?',
      'Bir kente gittiğinizde, müzeleri, tarihi yerleri gezer misiniz? (gezmek ister misiniz)',
      'Çeşitli atasözlerinin ve özdeyişlerin nereden çıktığını araştırmak ister misiniz?',
      'İnsanların ne düşündüklerini ve ne hissettiklerini incelemekten hoşlanır mısınız?',
      'Fen derslerinde öğrendiğiniz ilke ve kuralları evinizdeki sorunların çözümünde kullanır mısınız?',
      'Fen dersleri ile ilgili konularda sınıfla öğretilenlerden daha fazla bilgi edinmek için başka kaynaklara başvurduğunuz oluyor mu?',
      'Evcil hayvanların veya bitkilerin gelişmelerini incelemekten hoşlanır mısınız?',
      'Yeni öğrendiğiniz yabancı dildeki sözcükleri bir cümlede kullanmaya çalışır mısınız?',
      'Fen bilgisi ile ilgili problemleri çözmekten hoşlanır mısınız?',
      'Deniz dibindeki hayatı gösteren bir filmi ilgi ve dikkatle izler misiniz?',
      'Yabancı dildeki kelimeleri kolaylıkla ezberleyebiliyor musunuz?',
      'Bir bilyeyi, başka bir bilye ile vurarak, istediğiniz hedefe gönderebilir misiniz?',
      'Büyük coğrafya keşiflerini anlatan bir televizyon dizisini izlemekten hoşlanır mısınız?',
      'Tarih ve coğrafya derslerinde okutulan konuları kolay öğrenebiliyor musunuz?',
      'Bilimsel proje sergilerini gezer misiniz? (Gezmek ister misiniz)',
      'İnsanların gazetelerde hangi haberleri merakla okuduklarını araştırmak ister misiniz?',
      'Tarih romanları okumaktan hoşlanır mısınız?',
      'Televizyonda bilimsel buluşları anlatan belgesel programları izler misiniz?',
      'Ünlü bilim adamlarının hayatını anlatan televizyon dizilerini izler misiniz?',
      'bir pastayı veya böreği, eşit olarak ve düzgün biçimde kesebilir misiniz?',
      '“Çocuklarda yaratıcılık” başlıklı bir makaleyi okumak ister misiniz?',
      'Çevrenizdeki insanların davranışlarının nedenlerini merak edip araştırır mısınız?',
      'Uzay araçlarının, roketlerin evrimini gösteren bir sergiyi izlemek ister misiniz?',
      'Ünlü toplum liderlerinin hayatını anlatan eserleri okumak veya filmleri izlemek ister misiniz?',
      '“İnsan hakları” konulu bir ödev hazırlayıp sınıfta sunmak ister misiniz?',
      'Küçük bir deliğe, ince bir çubuğu, deliğin kenarına değdirmeden sokabilir misiniz?',
      'Küçük bir şeklin (örneğin bir çiçek resminin) içini, dışarı taşırmadan sulu boya ile boyayabilir misiniz?',
      'Orta Asya’daki eski uygarlık eserlerini gösteren bir belgesel filmi izlemekten hoşlanır mısınız?',
      'Evinizde ipekböceği yetiştirip bakımını üstlenebilir misiniz?',
      'Kapı zili, kilit gibi ev aletlerini onarmaya çalışır mısınız?',
      'Tahtadan veya metalden oyuncaklar yapabilir misiniz?',
      'Yeni çiçek türleri yetiştirmeyi denemek ister misiniz?',
      'Bir yabancı turistle, bildiğiniz yabancı dille konuşmaya çalışır mısınız?',
      'Gelecekte yabancı dilinizi ilerletip o dilde yazılmış dergi ve kitapları okumayı düşünür müsünüz?',
      '“Hayvanat bahçesine getirilen hayvanların yeni çevreye uyum sorunları” konulu bir belgesel filmi ilgi ile izler misiniz?',
      'Bir çiftliğin yöneticisi olmayı düşünür müsünüz?',
      'Yeni öğrendiğiniz yabancı dildeki sözcükleri doğru biçimde söylemeye gayret eder misiniz?',
      'Kaliteli meyve yetiştiren bir üretici olmayı düşünür müsünüz?',
      'Bir aleti parçalara ayırıp tekrar birleştirebilir misiniz?',
      'Evcil hayvanların hangi koşullarda ve ortamda daha iyi geliştiklerini incelemekten hoşlanır mısınız?',
      'Yeni bir alet veya makine ile karşılaştığınızda, hemen onun nasıl çalıştığını öğrenmeye çalışır mısınız?',
      'Evde bir hayvan (kuş) besler, bakımını yapar mısınız?',
      'Saksıda ve bahçede çiçek yetiştirip bakımını üstlenir misiniz?',
      'Elektrikli aletlerin nasıl işlediklerini inceler misiniz?',
      'Havuzlarda balık üretme yöntemlerini gösteren bir filmi ilgi ile izler misiniz?',
      'Her türlü araç ve gereç sağlansa, bir kafes yapmayı dener misiniz?',
      'İnanç ve düşüncelerinizi başkalarına kolaylıkla aktarabilir misiniz?',
      'Tartışmalarda güçlü kanıtlar bularak, görüşünüzü karşınızdakilere kabul ettirebilir misiniz?',
      'Belleğiniz kuvvetli midir?',
      'İnsanların daha çok hangi malları almak istediklerini öğrenmeye çalışır mısınız?',
      'Model uçak yapmaya çalışır mısınız?',
      'Arkadaşlarınız arasındaki çatışmaların çözümünde arabuluculuk yapar mısınız?',
      'Bir yazıdaki hataları düzeltmekten, bir hesabı kontrol etmekten hoşlanır mısınız?',
      'Yaptığınız herhangi bir işin temiz ve özenli olması için gereken özeni gösterir misiniz?',
      'Bir makinanın, örneğin bir elektrik motorunun, evrimini gösteren bir sergiyi gezmek ister misiniz?',
      'Çevreniz de “Hazırcevap” bir kişi olarak tanınır mısınız?',
      'Okul kantini ya da kooperatifini yönetmek ister misiniz?',
      'Bir işin ince ayrıntıları ile uğraşır mısınız?',
      'Paranızı nerelerde harcadığınızın kaydını tutar mısınız?',
      'Anılarınızı yazar mısınız?',
      'Yaz aylarında bir dükkanda ya da ticarethanede çalışmak ister misiniz?',
      'Derslerinize günü gününe çalışır mısınız?',
      'Okulda şiir okuma yarışmaları düzenleyen bir grubun üyesi olmak ister misiniz?',
      'Mektuplarınızı eski okul karnelerinizi tarih sırasına koyup saklar mısınız?',
      'Aldığınız her şeyin ya da yaptığınız her işin düzenli bir biçimde kaydını tutar mısınız?',
      'Yabancı dil kurslarına gitmek ister misiniz?',
      'Bir makinanın çalışmasını geliştirici yöntemler düşünür müsünüz?',
      'Söz ve davranışlarınızın başkaları üzerindeki etkilerini öğrenmeye çalışır mısınız?',
      'Konuşurken çevrenizdeki insanların ilgisini çekebilir ve görüşlerinizi onlara kabul ettirebilir misiniz?',
      'Televizyondaki reklamların daha iyi nasıl yapılabileceği üzerinde araştırma yapan bir grubun içinde yer almak ister misiniz?',
      'Evleri dolaşıp bir malın tanıtımını yapmaktan hoşlanır mısınız?',
      'Ödevlerinizi zamanında ve düzgün biçimde yapar mısınız?',
      'Televizyonda veya radyoda şiir saatlerini izler misiniz?',
      'Kendini gelecekte bir yazar olarak düşlediğiniz olur mu?',
      'Yaptığınız her hangi bir şeyi özenle süsler misiniz?',
      'Küçük hikayeler yazmayı dener misiniz?',
      'Ünlü sanatçıların, ressamların hayatını merak eder misiniz?',
      'Çevrenizdeki çeşitli makinaların bakımını yapar, onları bozmadan kullanabilir misiniz?',
      'Sizin gibi düşünmeyen insanları ikna etmek için uzun tartışmalara girer misiniz?',
      'Çevrenizdeki eşyaların, ürünlerin, satılsalar kaç lira edeceklerini düşünür müsünüz?',
      'Eşyalarınızı yerli yerine koyar, çevrenizi düzenli tutar mısınız?',
      'Bir malı satmak için neler yapmak gerektiğini öğreten bir kursa katılmak ister misiniz?',
      'Gazete, boş şişe gibi kullanılmış şeyleri satarak para kazanmayı düşünür müsünüz?',
      'Yabancı dilde şarkı söylemeye özenir misiniz?',
      'Mektupları zamanında cevaplandırır mısınız?',
      'Bir şeyi satın alacağınız zaman çeşitli dükkanları dolaşıp fiyatları karşılaştırarak gereğini duyar mısınız?',
      'Bir aleti, tarifesine ve şemasına bakarak çalıştırabilir misiniz?',
      'Güzel konuşma ve başkalarını ikna edebilme gücünü geliştirici kurslara katılmak ister misiniz?',
      'Arkadaşlarınıza ciklet, çikolata, bilye vb. şeyler sattınız mı?',
      'Gelecekte kendinizi bir tüccar olarak düşlediğiniz olur mu?',
      'Roman, hikaye veya şiir okur musunuz?',
      'Boş vakitlerinizde çiçek, nakış, resim, heykel vb. yapar mısınız?',
      'Radyo ve televizyonda müzik programlarını isler misiniz?',
      'Müzik yarışmalarına katılmak ister misiniz?',
      'Televizyonda resim sanatı ile ilgili haberleri ilgi ile izler misiniz?',
      'Gittiğiniz bir kentte sanat galerilerini, resim sergilerini gezmek ister misiniz?',
      'Ağlayan bir çocuğu oyalayabilir misiniz?',
      'Yaşlılar yurdunda eğlence günleri düzenlemekten hoşlanır mısınız?',
      'Başkalarına kişisel sorunların çözümünde yardımcı olabiliyor muşunuz?',
      'Çocuk gürültüsüne katlanabilir misiniz?',
      'Belli bir anda pek çok şeye birden dikkat edebilir misiniz?',
      'Kompozisyon derslerinde başarılı mısınız?',
      'Okul gazetesine yazı yazar mısınız? (Yazmak ister misiniz?)',
      'Müzik dersleri alıyor musunuz veya almak ister misiniz?',
      'Bir müzik aleti çalar mısınız?',
      'Bir hastaya bakabilir, ilaçlarını zamanında verebilir misiniz?',
      'Resim ve mimarlık sanatının gelişimini anlatan bir kitabı zevkle okur musunuz?',
      'Bir hastanede, yaz aylarında gönüllü olarak çalışmak ister misiniz?',
      'Boş vakitlerinizi resim veya el işleri yaparak geçirmeye çalışır mısınız?',
      'Konuştuğunuz zaman kendinizi çevrenizdeki insanlara dinletebiliyor musunuz?',
      'Karşınızdaki insanların ne düşündükleri ve ne hissettiklerini anlayabilir misiniz.',
      'Müzik aletleri sergisini gezmek ister misiniz?',
      'Çeşitli ülkelerin halk şarkılarını tanıtan bir program izler misiniz?',
      'Hastalar ve yaşlılara kitap okumaktan hoşlanır mısınız?',
      'Küçük çocuklara oyun öğretmekten, onlara şarkı söylemekten hoşlanır mısınız?',
      'İmkanlarınız ölçüsünde konserlere gitmeye çalışır mısınız?',
      'Yabancı dil dersinde başarılı mısınız?',
      'Ayakta ve hareketli olarak çalışmaktan hoşlanır mısınız?',
      'Ufak tefek besteler yapmaya çalışır mısınız?',
      'Bir evi ya da salonu süslemekten hoşlanır mısınız?',
      'Başkalarına dinletecek düzeyde bir müzik aleti çalıyor musunuz?',
      'Odanızı, yaptığınız resim veya el işleri ile süsler misiniz?',
      'El sanatları ya da resim kurslarına gitmek ister misiniz?',
      'Yeni duyduğunuz bir müzik parçasını çalmaya veya söylemeye çalışır mısınız?',
      'Gazete ve dergilerdeki edebiyat sütunlarını okur musunuz?',
      'Okul kitaplığına gider ve kitap alır mısınız?',
      'Dilbilgisi kurallarını öğrenip uygulayabiliyor musunuz?',
      'Görüşlerinize karşı çıkıldığında bunu soğukkanlılıkla karşılar mısınız?',
      'Açık havada çalışmaktan hoşlanır mısınız?',
      'Gelecekte kendinizi çeşitli dillerin yapı ve özellikleri üzerinde çalışan bir araştırmacı olarak düşünebilir misiniz?',
    ];

    return List.generate(texts.length, (i) {
      final qIndex = i + 37;
      return SurveyQuestion(
        id: 'q$qIndex',
        text: texts[i],
        type: SurveyQuestionType.singleChoice,
        isRequired: true,
        options: ['A', 'B', 'C', 'D'],
      );
    });
  }
}
