// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rUxB--1WMG1p1Rbqn4y8i918OTI_vPk',
    appId: '1:158619513037:web:72ea508d1c57c6a50eb984',
    messagingSenderId: '158619513037',
    projectId: 'edukn-23036',
    authDomain: 'edukn-23036.firebaseapp.com',
    storageBucket: 'edukn-23036.firebasestorage.app',
    measurementId: 'G-FN2B30TL7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwzYhQWI8Iv2-bozPEBrFT-p8WDoKW9o',
    appId: '1:158619513037:android:1ac596fbfd2d1bf80eb984',
    messagingSenderId: '158619513037',
    projectId: 'edukn-23036',
    storageBucket: 'edukn-23036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvnnopTUDnt3vXphOt2Pju5AI5AOMOxU',
    appId: '1:158619513037:ios:8cc1dc123e894f720eb984',
    messagingSenderId: '158619513037',
    projectId: 'edukn-23036',
    storageBucket: 'edukn-23036.firebasestorage.app',
    iosBundleId: 'com.example.edukn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvnnopTUDnt3vXphOt2Pju5AI5AOMOxU',
    appId: '1:158619513037:ios:8cc1dc123e894f720eb984',
    messagingSenderId: '158619513037',
    projectId: 'edukn-23036',
    storageBucket: 'edukn-23036.firebasestorage.app',
    iosBundleId: 'com.example.edukn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3rUxB--1WMG1p1Rbqn4y8i918OTI_vPk',
    appId: '1:158619513037:web:7241056b372bda010eb984',
    messagingSenderId: '158619513037',
    projectId: 'edukn-23036',
    authDomain: 'edukn-23036.firebaseapp.com',
    storageBucket: 'edukn-23036.firebasestorage.app',
    measurementId: 'G-440L9J8983',
  );
}
